//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMFGlobalFundingRates.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMF_London_2
    {
        public int Id { get; set; }
        public string Currency { get; set; }
        public string Product { get; set; }
        public string ON { get; set; }
        public string OneMonth_Indexed { get; set; }
        public string OneMonth_FixedValue { get; set; }
        public string ThreeMonth_Indexed { get; set; }
        public string ThreeMonth_FixedValue { get; set; }
    }
}
