//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMFGlobalFundingRates.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMF_Singapore
    {
        public int Id { get; set; }
        public string Currency { get; set; }
        public string Product { get; set; }
        public string ON_Repo { get; set; }
        public string OneMonth_Fixed { get; set; }
        public string TwoMonth_Fixed { get; set; }
        public string ThreeMonth_Fixed { get; set; }
        public string FourMonth_Fixed { get; set; }
        public string FiveMonth_Fixed { get; set; }
        public string SixMonth_Fixed { get; set; }
    }
}
