//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMFGlobalFundingRates.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CMF_Toronto> CMF_Toronto { get; set; }
        public virtual DbSet<CMF_Contacts> CMF_Contacts { get; set; }
        public virtual DbSet<CMF_NewYork> CMF_NewYork { get; set; }
        public virtual DbSet<CMF_London_1> CMF_London_1 { get; set; }
        public virtual DbSet<CMF_London_2> CMF_London_2 { get; set; }
        public virtual DbSet<CMF_Singapore> CMF_Singapore { get; set; }
        public virtual DbSet<CMF_Table_LastModifiedBy> CMF_Table_LastModifiedBy { get; set; }
    }
}
